/// Flutter icons MyCustomIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
// /
///
///
///
import 'package:flutter/widgets.dart';

class MyCustomIcons {
  MyCustomIcons._();

  static const _kFontFam = 'MyCustomIcons';
  static const String? _kFontPkg = null;

  static const IconData grape =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flag =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData manufacturer =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData taste =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData aroma =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
